import type { Metadata } from "next";
import "@fontsource/press-start-2p";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/navigation/AppSidebar";
import AppChrome from "@/components/navigation/AppChrome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#f6f6f7] text-black">
        <div className="min-h-screen">
          <AppSidebar />
          <AppChrome>{children}</AppChrome>
        </div>
      </body>
    </html>
  );
}
